import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import {
  Roboto_Flex as RobotoFlex,
  Roboto_Serif as RobotoSerif,
} from 'next/font/google'

import { ThemeProvider } from '@/lib/theme-provider'

const robotoFlex = RobotoFlex({
  subsets: ['latin'],
  variable: '--font-roboto-flex',
})
const robotoSerif = RobotoSerif({
  subsets: ['latin'],
  variable: '--font-roboto-serif',
})

export const metadata: Metadata = {
  title: 'Pedro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      suppressHydrationWarning
      className={`${robotoFlex.variable} ${robotoSerif.variable} font-sans`}
    >
      <body className="min-h-screen bg-light-bg text-light-primary dark:bg-dark-bg dark:text-dark-primary">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
