import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import {
  Roboto_Flex as RobotoFlex,
  Roboto_Serif as RobotoSerif,
} from 'next/font/google'

const robotoFlex = RobotoFlex({
  subsets: ['latin'],
  variable: '--font-roboto-flex',
})
const robotoSerif = RobotoSerif({
  subsets: ['latin'],
  variable: '--font-roboto-serif',
})

export const metadata: Metadata = {
  title: 'Pedro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="pt-br"
      className={`${robotoFlex.variable} ${robotoSerif.variable} font-sans`}
    >
      <body className="bg-zinc-50">
        <Header />
        {children}
      </body>
    </html>
  )
}
